### ISSUE TITLE
Can't pipe output

### ISSUE THREAD

**Issue by Yugloocamai** [remko/gulp-hashsum#8]
There doesn't seem to be a way to pipe the output to do some other work with gulp, only to write a file directly.  This makes the plugin fairly inflexible.  It would be best to follow gulp standards and allow the output to be piped to the next task.

**Comment by Yugloocamai** [comment]
Yes, or at least a way to optionally assign a gulp.dest() to the options.dest.  My main blocker was that I couldn't control the destination in a gulp-standards way.  Thanks for the quick response.

**Comment by remko** [comment]
Changed my mind, and used `stream` option instead.
